from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from schemer.analysis.roles import (
    RoleSource,
    component_roles,
    module_functions,
    module_representations,
    module_sheets,
    schematic_properties,
)
from schemer.analysis.topology import connectivity_digest
from schemer.core.errors import ToolchainError
from schemer.integration.toolchain import evaluate_zener
from schemer.source.hints import parse_hints
from schemer.source.shadow import materialize_proposal_shadow


def _components(schematic: dict[str, Any]) -> dict[str, dict[str, Any]]:
    root = schematic["root_ref"]
    return {ref.removeprefix(root + "."): item
            for ref, item in schematic["instances"].items()
            if item.get("kind") == "Component"}


def _source_digest(workspace: Path) -> str:
    sources = []
    for path in sorted(workspace.rglob("*")):
        relative = path.relative_to(workspace)
        if any(part.startswith(".") or part == "layout" for part in relative.parts):
            continue
        if not path.is_file() or path.suffix not in {".zen", ".kicad_sym", ".toml"}:
            continue
        content = path.read_text()
        if path.suffix == ".zen":
            if any(h.kind == "right-of" for h in parse_hints(content)):
                raise ToolchainError(f"spatial hints are not permitted in preparation: {relative}")
            content = "\n".join(line for line in content.splitlines()
                                if not line.lstrip().startswith("# pcb:sch "))
        sources.append((str(relative), content))
    return hashlib.sha256(json.dumps(sources).encode()).hexdigest()


def _evaluated_digest(schematic: dict[str, Any]) -> str:
    """Include resolved symbols and intent, including tool-managed dependencies."""
    root = schematic["root_ref"]
    # Module __signature includes compiler-local net IDs, not durable intent.
    # Physical attributes include the resolved symbol/value/assembly contract.
    values = {ref.removeprefix(root): (item.get("attributes", {})
                                     if item.get("kind") == "Component"
                                     else schematic_properties(item))
              for ref, item in schematic["instances"].items()
              if item.get("kind") in {"Component", "Module"}}
    return hashlib.sha256(json.dumps(values, sort_keys=True).encode()).hexdigest()


def prepare_source(entrypoint: Path, output: Path, compiler: Path) -> Path:
    """Copy first, evaluate, and expose the entire physical review worklist."""
    output = output.expanduser().resolve()
    if output.exists() and (not output.is_dir() or any(output.iterdir())):
        raise ToolchainError("preparation output must be a new or empty directory")
    shadow = materialize_proposal_shadow(entrypoint, {}, output / "source")
    schematic = evaluate_zener(shadow.entrypoint, compiler)
    review = {
        "version": 1,
        "workspace": "source",
        "entrypoint": str(shadow.entrypoint.relative_to(output)),
        "baseline_connectivity": connectivity_digest(schematic),
        "prepared_source_digest": None,
        "prepared_evaluation_digest": None,
        "unresolved": [],
        "components": [{"path": ref, "reference": item.get("reference_designator"),
                        "reviewed": False, "intent": "", "symbol_review": "",
                        "annotation_not_needed": ""}
                       for ref, item in sorted(_components(schematic).items())],
    }
    (output / "source-facts.json").write_text(json.dumps(schematic, indent=2) + "\n")
    path = output / "preparation-review.json"
    path.write_text(json.dumps(review, indent=2) + "\n")
    (output / "PREPARATION.md").write_text(
        "# Source preparation — layout is blocked\n\n"
        "Review the copied source and every component in preparation-review.json. "
        "Follow docs/primary-hinting-agent.md: audit active-device datasheets and symbols, "
        "add evidenced roles, ownership and grouping to the source copy, and resolve "
        "material representation choices with the user. Do not invent spatial hints.\n\n"
        "For each worklist item, record intent and symbol review evidence, then mark "
        "reviewed true. Where no supported domain annotation is needed, explain why "
        "in annotation_not_needed; do not add fake roles merely to pass the gate. "
        "Record all unresolved questions in unresolved. Keep citations here or in "
        "a companion review, not in source properties.\n\n"
        "Run `schemer check-preparation preparation-review.json` after review. "
        "Pass the validated file with `--preparation-review` to layout. "
        "No coordinates or previews have been generated by prepare.\n"
    )
    return path


def _read_review(path: Path) -> dict[str, Any]:
    try:
        review = json.loads(path.read_text())
        if not isinstance(review, dict) or review.get("version") != 1:
            raise ValueError("unsupported review format")
        if any(not isinstance(review.get(key), str) or not review[key].strip()
               for key in ("workspace", "entrypoint")):
            raise ValueError("review requires workspace and entrypoint paths")
        return review
    except (OSError, ValueError) as exc:
        raise ToolchainError(f"cannot read preparation review {path}: {exc}") from exc


def validate_preparation(
    path: Path, entrypoint: Path, schematic: dict[str, Any], *, seal: bool = False,
) -> None:
    """Require a complete human/agent review, unchanged topology and current sources.

    This is a workflow gate, not an automated claim that a datasheet was understood.
    Layout geometry remains independently validated and reviewed afterwards.
    """
    path = path.expanduser().resolve()
    review = _read_review(path)
    prepared_entry = (path.parent / review.get("entrypoint", "")).resolve()
    workspace = (path.parent / review.get("workspace", "")).resolve()
    if prepared_entry != entrypoint.expanduser().resolve() or not prepared_entry.is_relative_to(
            workspace):
        raise ToolchainError("preparation review belongs to another entrypoint")
    components = _components(schematic)
    rows = review.get("components")
    if not isinstance(rows, list) or any(
            not isinstance(row, dict) or not isinstance(row.get("path"), str) for row in rows):
        raise ToolchainError("preparation review requires a component worklist")
    by_path = {row.get("path"): row for row in rows}
    if len(by_path) != len(rows) or set(by_path) != set(components):
        raise ToolchainError("preparation worklist does not match the complete component inventory")
    if review.get("baseline_connectivity") != connectivity_digest(schematic):
        raise ToolchainError("source preparation changed component inventory or connectivity")
    if review.get("unresolved") != []:
        raise ToolchainError("source preparation has unresolved questions; do not lay out yet")
    instances, root = schematic["instances"], schematic["root_ref"]
    component_roles(instances, tuple(RoleSource(root + "." + ref, item)
                                     for ref, item in components.items()))
    module_functions(instances)
    module_sheets(instances)
    module_representations(instances)
    for ref, row in by_path.items():
        if row.get("reviewed") is not True or any(
                not isinstance(row.get(key), str) or not row[key].strip()
                for key in ("intent", "symbol_review")):
            raise ToolchainError(f"source preparation incomplete: {ref}")
        full = root + "." + ref
        intent = [schematic_properties(instances.get(source, {}))
                  for source in (full, full.rsplit(".", 1)[0])]
        if not any(p and ("role" in p or "function" in p) for p in intent):
            reason = row.get("annotation_not_needed")
            if not isinstance(reason, str) or not reason.strip():
                raise ToolchainError(f"missing semantic annotation or reviewed exception: {ref}")
    digest = _source_digest(workspace)
    evaluated = _evaluated_digest(schematic)
    recorded = review.get("prepared_source_digest")
    resolved = review.get("prepared_evaluation_digest")
    if (recorded is not None and recorded != digest
            or resolved is not None and resolved != evaluated):
        raise ToolchainError("prepared sources changed; revisit the worklist before a new review")
    if seal:
        review["prepared_source_digest"] = digest
        review["prepared_evaluation_digest"] = evaluated
        path.write_text(json.dumps(review, indent=2) + "\n")
    elif recorded != digest or resolved != evaluated:
        raise ToolchainError("run schemer check-preparation after completing the source review")


def require_preparation(args: Any, schematic: dict[str, Any]) -> None:
    path = getattr(args, "preparation_review", None)
    if path is None:
        raise ToolchainError("layout requires source preparation; run schemer prepare, complete "
                             "its worklist, then supply --preparation-review")
    validate_preparation(path, args.entrypoint, schematic)


def check_preparation(path: Path, compiler: Path) -> Path:
    path = path.expanduser().resolve()
    review = _read_review(path)
    entrypoint = path.parent / review.get("entrypoint", "")
    validate_preparation(path, entrypoint, evaluate_zener(entrypoint, compiler), seal=True)
    return entrypoint
